### PR TITLE
syntax: fix whitespace on nested subshells

### LINKED ISSUE #814: syntax: trailing white space added after opening parenthesis '('
In the second example below, a trailing blank/ white space is inserted after first opening '(' symbol, this is indicated through '^'. The expectation is like in first example above. This seems to happen when opening a subshell first after opening brackets of another subshell.
shfmt is called without any parameters in this case.

```
#!/bin/bash

# OK - no blank
(
    cd .
    (echo "Hello world!")
)

# nok - blank ^ after first (
(^ 
    (echo "Hello world!")
)
```

### PR DESCRIPTION
**Pull request by riacataquian**
we want white space on nested subshells if its in a single line since
its ambiguous, eg we want `( (` over `((`

this shouldn't be the case for multiple lines- fix the logic that adds
white space to only do so if the two subshells are in the same line

fixes #814

### CODE REVIEW

File: syntax/printer.go [hunk 1]
```diff
@@ -1081,6 +1081,13 @@ func (p *Printer) command(cmd Command, redirs []*Redirect) (startRedirs int) {
 		p.WriteByte('(')
 		if len(x.Stmts) > 0 && startsWithLparen(x.Stmts[0]) {
 			p.wantSpace = spaceRequired
+			if nested, ok := x.Stmts[0].Cmd.(*Subshell); ok {
```
Comment (mvdan) [inline syntax/printer.go:1084]: I would do this as part of startsWithLparen, which already looks into the type of the first command. Moreover, it multiple node types, which you will want to do as well (add tests too, please).

File: syntax/printer.go [hunk 2]
```diff
@@ -1081,6 +1081,13 @@ func (p *Printer) command(cmd Command, redirs []*Redirect) (startRedirs int) {
...
+				// we only want to keep the space between two nested subshells' open brackets
+				// if its in a single line to avoid ambiguity
+				if x.Lparen.Line() != nested.Pos().Line() {
```
Comment (mvdan) [inline syntax/printer.go:1087]: hmm, I'm not sure if this is exactly right - in some cases we'll add a newline, like:

```
$ cat f.sh
( (foo); bar)
$ shfmt f.sh | tr " \t" "*?"
(*
?(foo)
?bar
)
```

You can see that we add a space at the end of the line, which I replaced with `*` to make it visible. I think this edge case is still broken with your fix.

**Review by mvdan — COMMENTED** [review]
Some thoughts :)

File: syntax/printer.go (hunk 2 above)
Comment (riacataquian) [reply syntax/printer.go]: thanks for the tip! I added some more scenarios and test cases.

File: syntax/printer_test.go [hunk 3]
```diff
@@ -616,6 +616,24 @@ var printTests = []printCase{
...
+	{
+		"(\n(foo >redir)\n)",
+		"(\n\t(foo >redir)\n)",
+	},
+	{
+		"( (foo) )",
+		"( (foo))",
+	},
+	{
+		"( {foo}; bar; )",
```
Comment (mvdan) [inline syntax/printer_test.go:628]: Did you mean to use (foo) here? That's what we want to test AFAICT

It could also be nice to include a test for the other form of ambiguity when we add a newline:

( ((foo)); bar)

**Review by mvdan — APPROVED** [review]

File: syntax/printer_test.go (hunk 3 above)
Comment (riacataquian) [reply syntax/printer_test.go]: actually, will include fix :)

Comment (riacataquian) [reply syntax/printer_test.go]: @mvdan please see the latest [commit](https://github.com/mvdan/sh/pull/869/commits/8e4f46fc45ff1319f3cad818f5a78cd53ab2c17a) for my attempt to fix the scenario above.

File: syntax/printer.go [hunk 4]
```diff
@@ -1079,11 +1079,22 @@ func (p *Printer) command(cmd Command, redirs []*Redirect) (startRedirs int) {
 		p.ifClause(x, false)
 	case *Subshell:
 		p.WriteByte('(')
-		if len(x.Stmts) > 0 && startsWithLparen(x.Stmts[0]) {
+		stmts := x.Stmts
+		if len(stmts) > 0 && startsWithLparen(stmts[0]) {
 			p.wantSpace = spaceRequired
+			// we only want to keep the space between two nested subshells' open brackets
+			// if its in a single line to avoid ambiguity
+			if x.Lparen.Line() != stmts[0].Pos().Line() || len(stmts) > 1 && !p.singleLine {
```
Comment (mvdan) [inline syntax/printer.go:1087]:
```suggestion
			if (x.Lparen.Line() != stmts[0].Pos().Line() || len(stmts) > 1) && !p.singleLine {
```

the parentheses clarify whether the "and" or "or" apply first; otherwise it's a bit hard for a human to parse

File: syntax/printer.go [hunk 5]
```diff
@@ -1079,11 +1079,22 @@ func (p *Printer) command(cmd Command, redirs []*Redirect) (startRedirs int) {
...
+				p.wantSpace = spaceNotRequired
+
+				if p.minify {
+					p.newline(stmts[0].Pos())
```
Comment (mvdan) [inline syntax/printer.go:1091]: ah, so this was a bug? can we not just add it to the condition above, like singleLine?

**Review by mvdan — APPROVED** [review]
Tests LGTM, thanks! Just some code nits.

File: syntax/printer.go [hunk 6]
```diff
@@ -1079,11 +1079,22 @@ func (p *Printer) command(cmd Command, redirs []*Redirect) (startRedirs int) {
 		p.ifClause(x, false)
 	case *Subshell:
 		p.WriteByte('(')
-		if len(x.Stmts) > 0 && startsWithLparen(x.Stmts[0]) {
+		stmts := x.Stmts
+		if len(stmts) > 0 && startsWithLparen(stmts[0]) {
 			p.wantSpace = spaceRequired
+			// we only want to keep the space between two nested subshells' open brackets
+			// if its in a single line to avoid ambiguity
```
[the remark this answers is not in the document]
Comment (riacataquian) [reply syntax/printer.go:1086]: thanks! 😄

**Review by mvdan — APPROVED** [review]
